# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- auto-dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ./build.sh all -j
    ./build.sh clean
  displayName: 'make'
