# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- auto-dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ./build.sh all -j
    ./build.sh clean
  displayName: 'make main'
- script: |
    cd LinxSrvc/test
    git clone https://github.com/google/googletest.git
    git pull
    if [ ! -d "build" ]; then mkdir build && cd build; fi;
    cmake ..
    make -j
    ./test
  displayName: 'make test'
