# C/C++ with GCC

trigger:
- auto-dev

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    ./build.sh all -j
  displayName: 'make exec'
- script: |
    ./build.sh test
  displayName: 'make test-cov'
- script: |
    ./build.sh clean
  displayName: 'clean all'
